Merge PR

diff --git a/.github/workflows/auto-merge.yml b/.github/workflows/auto-merge.yml
--- a/.github/workflows/auto-merge.yml
+++ b/.github/workflows/auto-merge.yml
@@ -40,15 +40,15 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
-      # - name: Merge Pull Request
-      #   id: merge-pr
-      #   run: |
-      #     if gh pr merge ${{ env.pr_number }} --merge 
-      #     then
-      #       echo "Pull request #${{ env.pr_number }} merged successfully."
-      #     else
-      #       echo "Failed to merge pull request #${{ env.pr_number }}."
-      #       exit 1
-      #     fi
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Merge Pull Request
+        id: merge-pr
+        run: |
+          if gh pr merge ${{ env.pr_number }} --merge 
+          then
+            echo "Pull request #${{ env.pr_number }} merged successfully."
+          else
+            echo "Failed to merge pull request #${{ env.pr_number }}."
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
