CJECK1

diff --git a/.github/workflows/merging_process.yml b/.github/workflows/merging_process.yml
--- a/.github/workflows/merging_process.yml
+++ b/.github/workflows/merging_process.yml
@@ -94,12 +94,17 @@ jobs:
 
       - name: Merge PR
         id: merge-pr
-        if: env.pr_mergeable == 'true'
         run: |
-          PR_NUMBER=${{ env.pr_number }}
-          if gh pr merge $PR_NUMBER --merge 
+          if env.pr_mergeable == 'true'
           then
-            echo "Pull request $PR_NUMBER merged successfully"
+            PR_NUMBER=${{ env.pr_number }}
+            if gh pr merge $PR_NUMBER --merge 
+            then
+              echo "Pull request $PR_NUMBER merged successfully"
+            else
+              echo "Failed to merge pull request $PR_NUMBER"
+              exit 1
+            fi
           else
             echo "Failed to merge pull request $PR_NUMBER"
             exit 1
